Counter example
hx/esp pull request #3
Opened 2021-10-08 05:55 UTC by WillemHoman

Simple example to demonstrate basics of implementing a builder and model

https://user-images.githubusercontent.com/2238749/136505460-a0a1592b-dad1-425f-a5af-805cf4ff5615.mov

@hx

2021-10-10 21:15 UTC, hx requested changes
Thanks @WillemHoman for this nice addition!

Any particular reason to remove `package-lock.json`? I would imagine from my work with gems that you would exclude them only from libraries intended for use in other projects, which this project is not.

2021-10-10 21:15 UTC, hx commented on .gitignore
> +.idea
This is a local environment [thing that you can do for your whole machine](https://stackoverflow.com/questions/7335420/global-git-ignore).

2021-10-10 21:15 UTC, hx commented on src/index.ts
> +import { createCounterBuilder } from './examples/counter/builder'
Please add `examples/counter/index.ts`.

I should have done this for `examples/order` as well but I was in a bit of a rush.

2021-10-10 21:15 UTC, hx commented on src/examples/counter/Counter.ts
> +}
What do you think about making this a simple numeric type instead? I see it as a good opportunity to demonstrate that models can be _anything_, not just objects with properties.

```suggestion
type Counter = number
```

You could simplify further by removing the `Counter` type completely and just using `number` directly.

2021-10-12 07:26 UTC, WillemHoman commented
> Any particular reason to remove `package-lock.json`? 
It hasn't been removed, if you expand it in file view there are a couple of changes.

I think I deleted `package-lock.json` at one point and subsequently did an `npm install` which made this new  `package-lock.json`.

> I would imagine from my work with gems that you would exclude them only from libraries intended for use in other projects, which this project is not.
Agreed

2021-10-20 23:53 UTC, closed without merging